- name: Atualiza cache 
  apt:
    update_cache: yes

- name: Instalar docker 
  apt:
    name: 
     - docker-ce 
     - docker-ce-cli 
     - containerd.io 
     - docker-buildx-plugin 
     - docker-compose-plugin
    state: latest

- name: Baixar Docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose  
    mode: 0755

- name: install python 3
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: Install Docker SDK for Python
  pip:
    name: "docker<5" 
  become: yes

# - name: Baixar uma imagem 
#   docker_image:
#     name: leobittes/viacep-docker:1.0
#     source: pull


- name: iniciar contêineres do Docker
  become: true
  docker_container:
    name: desafio-06
    image: leobittes/viacep-docker:1.0
    state: started
    restart_policy: always
    ports:
      - "80:80"

# - name: Para o container
#   docker_container:
#     name: desafio-06
#     state: stopped      

   